#!/bin/bash

usage()
{
    echo "
Jak używać: ipxe [ -d ] [ -c ... ] | [ -h ]

 -d ściągnij źródła
 -c kompiluj - jaki iPXE budować
           q: buduję go dla mojej domowej sieci LAN (serwer q).
        omv1: buduję go dla mojej domowej sieci LAN (serwer omv1).
    internet: iPXE dla konfiguracji z poza sieci -z-.

 -h wyświetlenie tej instrukcji
"
}

if [ "$#" = 0 ]; then
    usage
    exit 1
fi

while [ "$1" != "" ]; do
    case $1 in
        -d )          download="yes"
                                ;;
        -c )          shift
                      net=$1
                      compile="yes"
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 0
    esac
    shift
done

cd
mkdir -p ~/tmp/ipxe
mkdir -p ~/tmp/ipxe-image

if [ "$download" = "yes" ]; then
    cd ~/tmp
    rm -rf ipxe
    git clone git://git.ipxe.org/ipxe.git
    rm -rf ipxe-custom
    git clone https://github.com/zbychuk79/ipxe-custom.git
fi

if [ "$compile" = "yes" ]; then
                       #cp ~/tmp/ipxe-custom/general.h ~/tmp/ipxe/src/config/general.h
    case $net in
        q )            cp ~/tmp/ipxe-custom/$net.ipxe ~/tmp/ipxe/src/embeded.ipxe
                                ;;
        omv1 )         cp ~/tmp/ipxe-custom/$net.ipxe ~/tmp/ipxe/src/embeded.ipxe
                                ;;
        internet )     cp ~/tmp/ipxe-custom/$net.ipxe ~/tmp/ipxe/src/embeded.ipxe
                                ;;
        * )            echo "
Nie podałeś parametru -c [ q | o1 | omv1 | internet ]
"
                       exit 0
    esac
    mkdir -p ~/tmp/ipxe-image/$net
    cd ~/tmp/ipxe/src
    make clean
    make all EMBED=embeded.ipxe
    make bin-x86_64-efi/ipxe.efi EMBED=embeded.ipxe
    cp bin/ipxe.lkrn bin/ipxe.usb bin/ipxe.iso bin/ipxe.dsk bin/ipxe.pxe bin-x86_64-efi/ipxe.efi ~/tmp/ipxe-image/$net
    cp ~/tmp/ipxe/src/config/general.h ~/tmp/ipxe-image/$net/
    cp embeded.ipxe ~/tmp/ipxe-image/$net/
    cp $0 ~/tmp/ipxe-image/$net/
fi
